City:
    type: entity
    table: city
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 64
            fixed: false
            nullable: false
        slug:
            type: string
            length: 64
            fixed: false
            nullable: false
    manyToOne:
        state:
            targetEntity: State
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                state_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
