ConfigType:
    type: entity
    table: config_type
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 64
            fixed: false
            nullable: false
        slug:
            type: string
            length: 64
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
