Feedback:
    type: entity
    table: feedback
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        label:
            type: string
            length: 64
            fixed: false
            nullable: true
        content:
            type: text
            nullable: true
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        isFixed:
            type: string
            length: null
            fixed: false
            nullable: true
            column: is_fixed
        fixedAt:
            type: datetime
            nullable: true
            column: fixed_at
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        fixedBy:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fixed_by_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
