Message:
    type: entity
    table: message
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        subject:
            type: string
            length: 145
            fixed: false
            nullable: true
        content:
            type: text
            nullable: true
        isSeen:
            type: boolean
            nullable: true
            column: is_seen
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    manyToMany:
        adminContact:
            targetEntity: AdminContact
            cascade: {  }
            mappedBy: message
            inversedBy: null
            joinTable: null
            orderBy: null
    manyToOne:
        parent:
            targetEntity: Message
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                parent_id:
                    referencedColumnName: id
            orphanRemoval: false
        sender:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sender_id:
                    referencedColumnName: id
            orphanRemoval: false
        reciever:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                reciever_id:
                    referencedColumnName: id
            orphanRemoval: false
        firstDelete:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                first_delete_id:
                    referencedColumnName: id
            orphanRemoval: false
        secondDelete:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                second_delete_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
