Post:
    type: entity
    table: post
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 64
            fixed: false
            nullable: false
        content:
            type: text
            nullable: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        score:
            type: integer
            unsigned: false
            nullable: true
        type:
            type: integer
            unsigned: false
            nullable: false
    manyToMany:
        comment:
            targetEntity: Comment
            cascade: {  }
            mappedBy: null
            inversedBy: post
            joinTable:
                name: post_has_comment
                joinColumns:
                    -
                        name: post_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: comment_id
                        referencedColumnName: id
            orderBy: null
    manyToOne:
        author:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                author_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
