WishItem:
    type: entity
    table: wish_item
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        isPosessed:
            type: boolean
            nullable: false
            column: is_posessed
    manyToOne:
        boardFolder:
            targetEntity: BoardFolder
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                board_folder_id:
                    referencedColumnName: id
            orphanRemoval: false
        product:
            targetEntity: Product
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
