imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: WuCore\FrontBundle\Entity\User

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
      default_connection: front
      connections:
        front:
            driver:   %database_driver%
            host:     %database_host%
            port:     %database_port%
            dbname:   %database_name_front%
            user:     %database_user%
            password: %database_password%
            charset:  UTF8
            mapping_types:
              enum: string
        products:
            driver:   %database_driver%
            host:     %database_host%
            port:     %database_port%
            dbname:   %database_name_product%
            user:     %database_user%
            password: %database_password%
            charset:  UTF8
            mapping_types:
              enum: string
        stats:
            driver:   %database_driver%
            host:     %database_host%
            port:     %database_port%
            dbname:   %database_name_stat%
            user:     %database_user%
            password: %database_password%
            charset:  UTF8
            mapping_types:
              enum: string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: front
        entity_managers:
          front:
            connection: front
            mappings:                    
              WuCoreFrontBundle:
                dir: Entity/
          products:
            connection: products
            mappings:                 
              WuCoreProductBundle:
                dir: Entity/
          stats:
            connection: stats
            mappings:                 
              WuCoreStatsBundle:
                dir: Entity/

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
