Acquirements:
    type: entity
    table: acquirements
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        purchasedAt:
            type: date
            nullable: false
            column: purchased_at
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    manyToOne:
        manufacturer:
            targetEntity: Manufacturer
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                manufacturer_id:
                    referencedColumnName: id
            orphanRemoval: false
        shop:
            targetEntity: Shop
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                shop_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
