AdminContact:
    type: entity
    repositoryClass: WuCore\CentralBundle\Repository\AdminContactRepository
    table: admin_contact
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        isClosed:
            type: boolean
            nullable: false
            column: is_closed
    manyToMany:
        message:
            targetEntity: Message
            cascade: {  }
            mappedBy: null
            inversedBy: adminContact
            joinTable:
                name: admin_contact_has_message
                joinColumns:
                    -
                        name: admin_contact_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: message_id
                        referencedColumnName: id
            orderBy: null
    manyToOne:
        handler:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                handler_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
