Config:
    type: entity
    repositoryClass: WuCore\CentralBundle\Repository\ConfigRepository
    table: config
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        valueName:
            type: string
            length: 64
            fixed: false
            nullable: true
            column: value_name
        value:
            type: text
            nullable: true
    manyToOne:
        configType:
            targetEntity: ConfigType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                config_type_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
