Picture:
    type: entity
    repositoryClass: WuCore\CentralBundle\Repository\PictureRepository
    table: picture
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        path:
            type: string
            length: 45
            fixed: false
            nullable: false
        mimeType:
            type: string
            length: 45
            fixed: false
            nullable: false
            column: mime_type
        uploadedAt:
            type: datetime
            nullable: false
            column: uploaded_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        label:
            type: string
            length: 45
            fixed: false
            nullable: false
        description:
            type: text
            nullable: true
        fileSize:
            type: string
            length: 45
            fixed: false
            nullable: false
            column: file_size
        isUsed:
            type: boolean
            nullable: false
            column: is_used
        width:
            type: integer
            unsigned: false
            nullable: false
        height:
            type: integer
            unsigned: false
            nullable: false
        xiff:
            type: text
            nullable: true
        credentials:
            type: array
            nullable: true
        isHighlighted:
            type: boolean
            nullable: false
            column: is_highlighted
    lifecycleCallbacks: {  }
